---
project:
  description: Amazon::Credentials
  author:
    name: Rob Lauer
    mailto: rclauer@gmail.com
pm-module: Amazon::Credentials
min-perl-version: 5.010
dependencies:
  requires: requires
  test-requires: test-requires
path:
  pm-module: lib
  exe-files: bin
  tests: t
extra-files:
  - ChangeLog
  - UnitTest.pm
  - release-notes.md
  - README-TESTING.md
  - README-BUILD.md
  - share:
      - README.md
resources:
  bugtracker:
    mailto: rclauer@gmail.com
    web: https://github.com/rlauer6/Amazon-Credentials/issues
  homepage: https://github.com/rlauer6/Amazon-Credentials
  repository:
    type: git
    url: git@github.com:rlauer6/Amazon-Credentials.git
    web: https://github.com/rlauer6/Amazon-Credentials
